"""Constants for the Odum - ElprisetJustNu integration."""
DOMAIN = "odum_elprisetjustnu"
DEVICE_IDENTIFIER = "elprisetjustnu"
ATTR_EPJNED = "EPJNED"
CURRENT_PRICE = "current_price"
DAY_AVERAGE_PRICE = "day_average_price"
DEFAULT_NAME = "ElprisetJustNu"
VAL_CURRENT_PRICE = "current_price"
VAL_DAY_AVERAGE_PRICE = "day_average_price"
API_URL = "https://www.elprisetjustnu.se"
UNIT_OF_M_PRICE = "SEK/kWh"
